### ISSUE TITLE
Cucumber version deprecated, please update this project to latest version

### ISSUE THREAD

**Issue by UdaySun** [protractor-cucumber-framework/protractor-cucumber-framework#191]
Hi Team,

Cucumber has been deprecated and now it is @cucumber/cucumber and the version is 7.0.0 would you please update this repo to reflect
![Npm_cucumber](https://user-images.githubusercontent.com/42842684/97937428-b137d380-1da4-11eb-8fdd-b2fbc8896df0.JPG)
 to latest

**Comment by prashanth-sams** [comment]
Need support for `@cucumber/cucumber`

**Comment by BarnitaG** [comment]
Is there any update on this, I'm too facing the issue since old version of cucumber deprecated, updating to latest cucumber gives error now. Kindly update if someone is looking into this.

**Comment by miquelolivares** [comment]
Also seeing an issue when updating to 7.0.0 `error TS2688: Cannot find type definition file for 'cucumber'.`
It seems related to this, as there are no issues on version 6

**Comment by beradrian** [comment]
I created a PR for this, maintaining backward compatibility too. Could you please merge it and release a new version? Thanks!

**Comment by ddsultan** [comment]
@beradrian, I tested the changes locally. It works perfectly other than the fact that I am getting the following error from cucumber itself (most probably): 

```sh
Error: TypeError: formatter.finished is not a function
node_modules/@cucumber/cucumber/src/cli/index.ts:138:25
node_modules/bluebird/js/release/util.js:16:23
```

**Comment by beradrian** [comment]
@ddsultan I investigated this and actually it's not from Cucumber. v7 accepts now only a formatter given as a class. I pushed a new commit to this PR.

**Comment by beradrian** [comment]
@ddsultan did you manage to test my latest commit? Thanks!

**Comment by francisrobitaille-ulaval** [comment]
any update?

**Comment by beradrian** [comment]
@ddsultan @AlexandrosD did you tested my PR? Everything fine? If not, please let me know so I can fix.

**Comment by AlexandrosD** [comment]
See https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/issues/73#issuecomment-762493006

**Comment by jan-molak** [comment]
Hey @AlexandrosD! Cucumber 7 has changed the structure and content of its internal events and uses [`cucumber-messages`](https://github.com/cucumber/messages-javascript) rather than the event protocol available in version 6.

I've just gone through a lengthy exercise of making [Serenity/JS](https://serenity-js.org) reporting engine compatible with Cucumber 7, and it can be now used with both [Serenity/JS reporting services](https://serenity-js.org/handbook/reporting/index.html) and [Cucumber-native reporters](https://github.com/cucumber/cucumber-js/tree/master/src/formatter) (as a [drop-in replacement](https://serenity-js.org/handbook/integration/serenityjs-and-protractor.html#using-native-cucumber-reporters) of `protractor-cucumber-framework`).

```
npm install --save-dev @serenity-js/protractor
```

```javascript
// protractor.conf.js
exports.config = {

    framework:      'custom',
    frameworkPath:  require.resolve('@serenity-js/protractor/adapter'),

    specs: [ 'features/*.feature', ],
    cucumberOpts: {
        format: [
            'html:cucumber.html',
            'snippets:snippets.txt',
            'summary:summary.txt',
            'usage:usage.txt',
            // etc
        ],
        require: [
            'features/step_definitions/**/*.ts',    // or *.js
        ],
        'require-module': ['ts-node/register'],     // to add support for TypeScript
        tags:    ['~@wip'],
        strict:  false,
    },

    // ... other Protractor config omitted for brevity 
};
```

Hope this helps!
Jan

**Comment by flaviencathala** [comment]
Should be fixed by release 7.0.0.

**Comment by ddsultan** [comment]
> @ddsultan @AlexandrosD did you tested my PR? Everything fine? If not, please let me know so I can fix.

Unfortunately, not because we stopped exploring this option
